-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 23:08:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_Medico_JYP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sistema_Medico_JYP` ;

-- -----------------------------------------------------
-- Schema Sistema_Medico_JYP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema_Medico_JYP` DEFAULT CHARACTER SET utf8 ;
USE `Sistema_Medico_JYP` ;

-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(255) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Correo_UNIQUE` ON `Sistema_Medico_JYP`.`Usuario` (`correo`);


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Sistema_Medico_JYP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_Usuario1_idx` ON `Sistema_Medico_JYP`.`Paciente` (`Usuario_idUsuario`) ;

CREATE UNIQUE INDEX `Usuario_idUsuario_UNIQUE` ON `Sistema_Medico_JYP`.`Paciente` (`Usuario_idUsuario`);


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Especialidad` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombreEspecialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Medico` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  `Especialidad_idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Sistema_Medico_JYP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidad`)
    REFERENCES `Sistema_Medico_JYP`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medico_Usuario1_idx` ON `Sistema_Medico_JYP`.`Medico` (`Usuario_idUsuario` ) ;

CREATE UNIQUE INDEX `Usuario_idUsuario_UNIQUE` ON `Sistema_Medico_JYP`.`Medico` (`Usuario_idUsuario` ) ;

CREATE INDEX `fk_Medico_Especialidad1_idx` ON `Sistema_Medico_JYP`.`Medico` (`Especialidad_idEspecialidad` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Cita` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `motivo` MEDIUMTEXT NULL,
  PRIMARY KEY (`idCita`),
  CONSTRAINT `fk_TicketCita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Sistema_Medico_JYP`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TicketCita_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `Sistema_Medico_JYP`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TicketCita_Paciente1_idx` ON `Sistema_Medico_JYP`.`Cita` (`Paciente_idPaciente` ) ;

CREATE INDEX `fk_TicketCita_Medico1_idx` ON `Sistema_Medico_JYP`.`Cita` (`Medico_idMedico` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`TicketCita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`TicketCita` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`TicketCita` (
  `idTicketCita` INT NOT NULL AUTO_INCREMENT,
  `codigoTicket` VARCHAR(45) NOT NULL,
  `Cita_idCita` INT NOT NULL,
  `codigoPago` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTicketCita`),
  CONSTRAINT `fk_TicketCita_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `Sistema_Medico_JYP`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TicketCita_Cita1_idx` ON `Sistema_Medico_JYP`.`TicketCita` (`Cita_idCita` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`ContactoEmergencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`ContactoEmergencia` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`ContactoEmergencia` (
  `idContactoEmergencia` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(40) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT NULL,
  PRIMARY KEY (`idContactoEmergencia`),
  CONSTRAINT `fk_ContactoEmergencia_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Sistema_Medico_JYP`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ContactoEmergencia_Paciente1_idx` ON `Sistema_Medico_JYP`.`ContactoEmergencia` (`Paciente_idPaciente` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Horario` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  CONSTRAINT `fk_Horario_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `Sistema_Medico_JYP`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Horario_Medico1_idx` ON `Sistema_Medico_JYP`.`Horario` (`Medico_idMedico` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`Pago` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `metodo` VARCHAR(45) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(45) NULL,
  `TicketCita_idTicketCita` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  CONSTRAINT `fk_Pago_TicketCita1`
    FOREIGN KEY (`TicketCita_idTicketCita`)
    REFERENCES `Sistema_Medico_JYP`.`TicketCita` (`idTicketCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_TicketCita1_idx` ON `Sistema_Medico_JYP`.`Pago` (`TicketCita_idTicketCita` ) ;


-- -----------------------------------------------------
-- Table `Sistema_Medico_JYP`.`DetallesHorario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_Medico_JYP`.`DetallesHorario` ;

CREATE TABLE IF NOT EXISTS `Sistema_Medico_JYP`.`DetallesHorario` (
  `idDetallesHorario` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idDetallesHorario`),
  CONSTRAINT `fk_DetallesHorario_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `Sistema_Medico_JYP`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DetallesHorario_Horario1_idx` ON `Sistema_Medico_JYP`.`DetallesHorario` (`Horario_idHorario` ) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- SELECT * FROM Usuario