-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 16:15:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CitasMedicasJYP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CitasMedicasJYP` ;

-- -----------------------------------------------------
-- Schema CitasMedicasJYP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CitasMedicasJYP` DEFAULT CHARACTER SET utf8 ;
USE `CitasMedicasJYP` ;

-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(255) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Correo_UNIQUE` ON `CitasMedicasJYP`.`Usuario` (`correo` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`ContactoEmergencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`ContactoEmergencia` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`ContactoEmergencia` (
  `idContactoEmergencia` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(40) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContactoEmergencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(20) NULL,
  `fecha_nacimiento` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `ContactoEmergencia_idContactoEmergencia` INT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CitasMedicasJYP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_ContactoEmergencia1`
    FOREIGN KEY (`ContactoEmergencia_idContactoEmergencia`)
    REFERENCES `CitasMedicasJYP`.`ContactoEmergencia` (`idContactoEmergencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_Usuario1_idx` ON `CitasMedicasJYP`.`Paciente` (`Usuario_idUsuario` ASC);

CREATE UNIQUE INDEX `Usuario_idUsuario_UNIQUE` ON `CitasMedicasJYP`.`Paciente` (`Usuario_idUsuario` ASC);

CREATE INDEX `fk_Paciente_ContactoEmergencia1_idx` ON `CitasMedicasJYP`.`Paciente` (`ContactoEmergencia_idContactoEmergencia` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Especialidad` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombreEspecialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Medico` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  `Especialidad_idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CitasMedicasJYP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidad`)
    REFERENCES `CitasMedicasJYP`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medico_Usuario1_idx` ON `CitasMedicasJYP`.`Medico` (`Usuario_idUsuario` ASC);

CREATE UNIQUE INDEX `Usuario_idUsuario_UNIQUE` ON `CitasMedicasJYP`.`Medico` (`Usuario_idUsuario` ASC);

CREATE INDEX `fk_Medico_Especialidad1_idx` ON `CitasMedicasJYP`.`Medico` (`Especialidad_idEspecialidad` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Cita` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `motivo` MEDIUMTEXT NULL,
  PRIMARY KEY (`idCita`),
  CONSTRAINT `fk_TicketCita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `CitasMedicasJYP`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TicketCita_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `CitasMedicasJYP`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TicketCita_Paciente1_idx` ON `CitasMedicasJYP`.`Cita` (`Paciente_idPaciente` ASC);

CREATE INDEX `fk_TicketCita_Medico1_idx` ON `CitasMedicasJYP`.`Cita` (`Medico_idMedico` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`TicketCita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`TicketCita` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`TicketCita` (
  `idTicketCita` INT NOT NULL AUTO_INCREMENT,
  `codigoTicket` VARCHAR(45) NOT NULL,
  `Cita_idCita` INT NOT NULL,
  `codigoPago` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTicketCita`),
  CONSTRAINT `fk_TicketCita_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `CitasMedicasJYP`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TicketCita_Cita1_idx` ON `CitasMedicasJYP`.`TicketCita` (`Cita_idCita` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Horario` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  CONSTRAINT `fk_Horario_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `CitasMedicasJYP`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Horario_Medico1_idx` ON `CitasMedicasJYP`.`Horario` (`Medico_idMedico` ASC);


-- -----------------------------------------------------
-- Table `CitasMedicasJYP`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CitasMedicasJYP`.`Pago` ;

CREATE TABLE IF NOT EXISTS `CitasMedicasJYP`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `metodo` VARCHAR(45) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(45) NULL,
  `TicketCita_idTicketCita` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  CONSTRAINT `fk_Pago_TicketCita1`
    FOREIGN KEY (`TicketCita_idTicketCita`)
    REFERENCES `CitasMedicasJYP`.`TicketCita` (`idTicketCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_TicketCita1_idx` ON `CitasMedicasJYP`.`Pago` (`TicketCita_idTicketCita` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- SELECT * FROM Usuario
-- SELECT * FROM Usuario WHERE correo = 'admin@citasmedicas.com'
