export enum Parentesco {
    PADRE = "Padre",
    MADRE = "Madre",
    CONYUGUE = "Conyugue",
    HIJO = "Hijo",
    HIJA = "Hija",
    HERMANO = "Hermano",
    HERMANA = "Hermana",
    TIO = "Tio",
    TIA = "Tia",
    PRIMO = "Primo",
    PRIMA = "Prima",
    ABUELO = "Abuelo",
    ABUELA = "Abuela",
    AMIGO = "Amigo",
    AMIGA = "Amiga",
    VECINO = "Vecino",
    VECINA = "Vecina",
    CONOCIDO = "Conocido",
    CONOCIDA = "Conocida",
    OTRO = "Otro"
}